services:
    install:
      network_mode: "host"
      image: cde/base 
      build:
        context: .
      volumes: 
        - ./root/.gitconfig:/root/.gitconfig
        - ./root/.p10k.zsh:/root/.p10k.zsh
        - ./root/.zshrc:/root/.zshrc
        - ./root/.config/nix:/root/.config/nix
        - ./root/.config/nvim:/root/.config/nvim
        - ./root/.config/lf:/root/.config/lf
        - ./root/.config/tmux/tmux.conf:/root/.config/tmux/tmux.conf
        # STATE
        - ./state/nix:/nix-state
        - ./state/root/.local:/root/.local
        - ./state/root/.config/gh:/root/.config/gh
        - ./state/root/.config/tmux/plugins:/root/.config/tmux/plugins
        - ./state/root/.config/.zsh:/root/.config/.zsh
      entrypoint: >
        sh -c "nix profile install path:/root/.config/nix/nvim-flake --priority 0;\
               rm -rvf /nix-state/* && \
               cp -rv /nix/* /nix-state && \
               /root/.tmux/plugins/tpm/bin/install_plugins && \
               zsh -c '/root/powerlevel10k/gitstatus/install'"

    nix:
      network_mode: "host"
      image: cde/base 
      build:
        context: .
      volumes: 
        - ./root/.gitconfig:/root/.gitconfig
        - ./root/.p10k.zsh:/root/.p10k.zsh
        - ./root/.zshrc:/root/.zshrc
        - ./root/.config/nix:/root/.config/nix
        - ./root/.config/nvim:/root/.config/nvim
        - ./root/.config/lf:/root/.config/lf
        - ./root/.config/tmux/tmux.conf:/root/.config/tmux/tmux.conf
        # STATE
        - ./state/nix:/nix
        - ./state/root/.local:/root/.local
        - ./state/root/.config/gh:/root/.config/gh
        - ./state/root/.config/tmux/plugins:/root/.config/tmux/plugins
        - ./state/root/.config/.zsh:/root/.config/.zsh
      entrypoint: sh -c "tmux -u"
