services:
    startup:
      network_mode: "host"
      image: cde/base 
      build:
        context: .
      volumes: 
        - ./state/nix/store:/nix-store
      entrypoint: sh -c "rm -rf /nix-store/* && cp -r /nix/store/* /nix-store"

    base:
      network_mode: "host"
      image: cde/base 
      build:
        context: .
      volumes: 
        - ./root/.config/:/root/.config
        - ./state/nix/store:/nix/store
