services:
  identity:
    init: true
    image: cde-identity
    build:
      context: ./
      dockerfile: ./identity/Dockerfile
      args:
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
    network_mode: "host"
    user: "${DEV_UID}:${DEV_GID}"
    working_dir: /home/${DEV_USER}/projects
    volumes:
      - /etc/hosts:/etc/hosts
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - ${HOME}/.Xauthority:/tmp/.Xauthority:ro 
      - ./base/root/.config/nvim/nvim-pack-lock.json:/home/${DEV_USER}/.config/nvim/nvim-pack-lock.json
      - ./base/root/.config/nvim/lua:/home/${DEV_USER}/.config/nvim/lua
      - ./base/root/.config/nvim/init_identity.lua:/home/${DEV_USER}/.config/nvim/init.lua
      - ./base/state/.config/gh:/home/${DEV_USER}/.config/gh
      - ./base/state/.local/share/nvim/site:/home/${DEV_USER}/.local/share/nvim/site
      - ./identity/state/projects:/home/${DEV_USER}/projects
      - ./identity/state/.ssh:/home/${DEV_USER}/.ssh
    environment:
      USER: ${DEV_USER}
      LOGNAME: ${DEV_USER}
      HOME: /home/${DEV_USER}
      SHELL: /bin/zsh
      TERM: xterm-256color
      COLORTERM: truecolor
      DISPLAY: $DISPLAY
      SSH_AUTH_SOCK: /ssh-agent
      XAUTHORITY: /tmp/.Xauthority
    tty: true
