services:
  identity:
    image: cde-identity
    build:
      context: ./new-profiles/identity
      args:
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
    network_mode: "host"
    user: "${DEV_UID}:${DEV_GID}"
    working_dir: /home/${DEV_USER}/projects
    volumes:
      - /etc/hosts:/etc/hosts
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - ${HOME}/.Xauthority:/tmp/.Xauthority:ro 
      - ./new-profiles/state/identity/projects:/home/${DEV_USER}/projects
      - ./new-profiles/state/identity/.ssh/known_hosts:/home/${DEV_USER}/.ssh/known_hosts
    environment:
      DISPLAY: $DISPLAY
      SSH_AUTH_SOCK: /ssh-agent
      XAUTHORITY: /tmp/.Xauthority
    tty: true
    stdin_open: true
