services:
  devcontainer:
    image: hubiboar/terraform:latest
    volumes:
      - ../..:/workspaces:cached
      -  /var/run/docker.sock:/var/run/docker.sock
      -  ~/.ssh:/root/.ssh
      -  ~/.gitconfig:/root/.gitconfig
    command: sleep infinity