#azurite -s -l /c/azurite -d /c/azurite/debug.log
#func host start --host localhost --port 7022 --pause-on-error --dotnet-isolated-debug

FROM hubiboar/dotnet:latest

#update
RUN apt-get -y update

#func
RUN apt-get install azure-functions-core-tools-4

#node
RUN apt-get install nodejs -y 
RUN apt-get install npm -y

#azurite
RUN npm install -g azurite