x-base: &base
  image: devdocker/cde
  build: ./setup/docker
  network_mode: "host"
  environment:
    PROFILE: $PROFILE
  volumes: 
    - /home/dotfiles:/home/dotfiles
    - /home/projects:/home/projects
    - /home/dotfiles/devdocker/setup/profiles/${PROFILE}/state:/state
    - /home/dotfiles/devdocker/setup/profiles/${PROFILE}/state/.local:/root/.local
    - /mnt/c:/mnt/c
    - /mnt/c/users/HUD/Desktop:/desktop
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/.docker:/root/.docker
    - /root/.azure:/root/.azure
    - /root/.config/gh:/root/.config/gh
    - /root/.aspnet:/root/.aspnet
    - /root/nis:/root/nis
    - ./setup/.ssh:/root/.ssh
    - ./setup/.gitconfig:/root/.gitconfig

services:
    base:
      image: cde/base 
      build:
        context: ./profiles/base

    dotnet:
      container_name: cde-dotnet
      build: 
        context: ./profiles/dotnet
      entrypoint: zsh 

    nis:
      container_name: cde-nis
      build:
        context: ./profiles/nis
      entrypoint: zsh 
