x-base: &base
  image: devdocker/cde
  build: ./setup/docker
  network_mode: "host"
  volumes: 
    - /home/dotfiles:/home/dotfiles
    - /home/projects:/home/projects
    - /home/dotfiles/dotfiles:/dotfiles
    - /mnt/c:/mnt/c
    - /mnt/c/users/HUD/Desktop:/desktop
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/.azure:/root/.azure
    - /root/.aspnet:/root/.aspnet
    - ./setup/startup:/startup
    - ./setup/.ssh:/root/.ssh
    - ./setup/.gitconfig:/root/.gitconfig

services:
  cde-base:
    <<: *base 
    container_name: cde-base
    profiles:
      - base
      - all
    environment:
      PROFILE: base
      # I wanted to use Volumes for setting separate states paths for each service but, could not merge the *base volumes with custom one 
      STATE_PATH: "/home/dotfiles/devdocker/setup/state/base"
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/runner/run.sh
      "

  cde-nisportal:
    <<: *base 
    container_name: cde-nisportal
    profiles:
      - nisportal
      - all
    environment:
      PROFILE: nisportal
      STATE_PATH: "/home/dotfiles/devdocker/setup/state/nisportal"
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/modules/dotnet/dotnet.sh
        && /startup/modules/dotnet/azcli.sh
        && /startup/modules/node/node.sh
        && /startup/modules/node/node-yarn.sh
        && /startup/runner/run.sh
      "
  cde-dotnet:
    <<: *base 
    container_name: cde-dotnet
    profiles:
      - dotnet
      - all
    environment:
      PROFILE: dotnet
      STATE_PATH: "/home/dotfiles/devdocker/setup/state/dotnet"
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/modules/dotnet/dotnet.sh
        && /startup/modules/dotnet/azcli.sh
        && /startup/runner/run.sh
      "
