services:
  devdocker:
    image: devdocker/cde
    build: ./setup/docker
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ../:/startup:cached
      - C:\Projects:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ./setup/.ssh:/root/.ssh
      - ./setup/.gitconfig:/root/.gitconfig
    command: sh -c "
        cd /startup/devdocker/setup/modules
        && ../runner/config.sh
        && ./dotnet.sh
        && ./azcli.sh
        && ../runner/run.sh
      "