x-base: &base
  image: devdocker/cde
  build: ./setup/docker
  network_mode: "host"
  environment:
    PROFILE: $PROFILE
  volumes: 
    - /home/dotfiles:/home/dotfiles
    - /home/projects:/home/projects
    - /home/dotfiles/dotfiles/.config/nvim:/dotfiles/.config/nvim
    - /home/dotfiles/dotfiles/.config/tmux:/dotfiles/.config/tmux
    - /home/dotfiles/dotfiles/.config/lf:/dotfiles/.config/lf
    - /home/dotfiles/dotfiles/root:/dotfiles
    - /home/dotfiles/devdocker/setup/profiles/${PROFILE}/nvim/plugins.lua:/dotfiles/.config/nvim/lua/plugins.lua
    - /home/dotfiles/devdocker/setup/profiles/${PROFILE}/state:/state
    - /home/dotfiles/devdocker/setup/profiles/${PROFILE}/state/tmux/plugins:/dotfiles/.config/tmux/plugins
    - /home/dotfiles/devdocker/setup/profiles/${PROFILE}/state/.local:/root/.local
    - /mnt/c:/mnt/c
    - /mnt/c/users/HUD/Desktop:/desktop
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/.docker:/root/.docker
    - /root/.azure:/root/.azure
    - /root/.aspnet:/root/.aspnet
    - ./setup/startup:/startup
    - ./setup/.ssh:/root/.ssh
    - ./setup/.gitconfig:/root/.gitconfig

services:
  cde-base:
    <<: *base 
    container_name: cde-base
    profiles:
      - base
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/runner/run.sh
      "

  cde-nis:
    <<: *base 
    container_name: cde-nis
    profiles:
      - nis
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/modules/dotnet/dotnet.sh
        && /startup/modules/dotnet/azcli.sh
        && /startup/modules/node/node.sh
        && /startup/modules/node/node-yarn.sh
        && /startup/runner/run.sh
      "
  cde-dotnet:
    <<: *base 
    container_name: cde-dotnet
    profiles:
      - dotnet
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/modules/dotnet/dotnet.sh
        && /startup/modules/dotnet/azcli.sh
        && /startup/runner/run.sh
      "
  cde-go:
    <<: *base 
    container_name: cde-go
    profiles:
      - go
    command: sh -c "
        chmod +x /startup/**/*.sh
        && /startup/runner/config.sh
        && /startup/modules/go/go.sh
        && /startup/runner/run.sh
      "
