services:
  devdocker:
    image: devdocker/cde
    build: ./setup/docker
    container_name: cde
    network_mode: "host"
    volumes:
      - ../:/startup:cached
      - /home/Projects:/workspaces:cached
      - /mnt/c/:/c:cached
      - /mnt/c/users/HUD/Desktop/:/desktop:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ./setup/.ssh:/root/.ssh
      - ./setup/.gitconfig:/root/.gitconfig
    command: sh -c "
        chmod 400 ~/.ssh/id_rsa
        && chmod +x /startup/devdocker/setup/runner/*.sh
        && chmod +x /startup/devdocker/setup/modules/*.sh
        && cd /startup/devdocker/setup/modules
        && /startup/devdocker/setup/runner/config.sh
        && ./dotnet.sh
        && ./azcli.sh
        && ./node.sh
        && ./node-yarn.sh
        && ../runner/run.sh
      "
