services:
  devdocker:
    image: hubiboar/cde:latest
    volumes:
      - .:/startup:cached
      - C:\Projects:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - .ssh:/root/.ssh
      - .gitconfig:/root/.gitconfig
    command: sh -c "
        cd /startup/modules
        && ./runner/config.sh
        && ./dotnet.sh
        && ./runner/run.sh
      "