# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
    inputs:
      tag_name:
        type: string
        description: Tag
        required: true
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DockerLogin: "hubiboar"
  Dockerfile: "devdocker/docker/Dockerfile.CDE"
  LatestTag: hubiboar/cde:latest
  VersionTag: hubiboar/cde:1.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login
      run: docker login -u "${{ env.DockerLogin }}" -p "${{ secrets.DOCKER_PASSWORD }}"


    - name: Build CDE
      run: docker build -t ${{ env.LatestTag }} -t ${{ env.VersionTag }} -f ${{ env.Dockerfile }} .

    - name: Push CDE
      run: docker push ${{ env.LatestTag }} && docker push ${{ env.VersionTag }}