# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
    inputs:
      tag_name:
        type: string
        description: Tag
        required: true
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DockerLogin: "hubiboar"
  UbuntuDockerfile: "docker/Dockerfile.ubuntu"
  UbuntuLatestTag: hubiboar/ubuntu:latest
  UbuntuVersionTag: hubiboar/ubuntu:1.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}
  DotnetDockerfile: "docker/Dockerfile.dotnet"
  DotnetLatestTag: hubiboar/dotnet:latest
  DotnetVersionTag: hubiboar/dotnet:8.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}
  FunctionsDockerfile: "docker/Dockerfile.functions"
  FunctionsLatestTag: hubiboar/functions:latest
  FunctionsVersionTag: hubiboar/functions:8.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}
  PythonDockerfile: "docker/Dockerfile.python"
  PythonLatestTag: hubiboar/python:latest
  PythonVersionTag: hubiboar/python:1.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}
  PandasDockerfile: "docker/Dockerfile.pandas"
  PandasLatestTag: hubiboar/pandas:latest
  PandasVersionTag: hubiboar/pandas:1.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}
  TerraformDockerfile: "docker/Dockerfile.terraform"
  TerraformLatestTag: hubiboar/terraform:latest
  TerraformVersionTag: hubiboar/terraform:1.0.0.${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login
      run: docker login -u "${{ env.DockerLogin }}" -p "${{ secrets.DOCKER_PASSWORD }}"


    - name: Build Ubuntu
      run: docker build -t ${{ env.UbuntuLatestTag }} -t ${{ env.UbuntuVersionTag }} -f ${{ env.UbuntuDockerfile }} .

    - name: Push Ubuntu
      run: docker push ${{ env.UbuntuLatestTag }} && docker push ${{ env.UbuntuVersionTag }}


    - name: Build Dotnet
      run: docker build -t ${{ env.DotnetLatestTag }} -t ${{ env.DotnetVersionTag }} -f ${{ env.DotnetDockerfile }} .

    - name: Push Dotnet
      run: docker push ${{ env.DotnetLatestTag }} && docker push ${{ env.DotnetVersionTag }}


    - name: Build Functions
      run: docker build -t ${{ env.FunctionsLatestTag }} -t ${{ env.FunctionsVersionTag }} -f ${{ env.FunctionsDockerfile }} .

    - name: Push Functions
      run: docker push ${{ env.FunctionsLatestTag }} && docker push ${{ env.FunctionsVersionTag }}


    - name: Build Python
      run: docker build -t ${{ env.PythonLatestTag }} -t ${{ env.PythonVersionTag }} -f ${{ env.PythonDockerfile }} .

    - name: Push Python
      run: docker push ${{ env.PythonLatestTag }} && docker push ${{ env.PythonVersionTag }}


    - name: Build Pandas
      run: docker build -t ${{ env.PandasLatestTag }} -t ${{ env.PandasVersionTag }} -f ${{ env.PandasDockerfile }} .

    - name: Push Pandas
      run: docker push ${{ env.PandasLatestTag }} && docker push ${{ env.PandasVersionTag }}


    - name: Build Terraform
      run: docker build -t ${{ env.TerraformLatestTag }} -t ${{ env.TerraformVersionTag }} -f ${{ env.TerraformDockerfile }} .

    - name: Push Terraform
      run: docker push ${{ env.TerraformLatestTag }} && docker push ${{ env.TerraformVersionTag }}
